### ISSUE TITLE
Wrap in Request/ResponeEntity

### ISSUE THREAD

**Issue by VladimirKondr** [10-13/TcpP2P#10]
Wrap requests and responses in ClientServerController in wrappers. You can find examples in playground.Server2Controller

**Comment by 10-13** [comment]
Where i can find request wrapers examples? May be ment requsts through RestTemplate?
In [file](https://github.com/10-13/TcpP2P/blob/develop/src%2Fmain%2Fjava%2FKilimanJARo%2FP2P%2Fplayground%2FServer2Application.java#L152) only usual requests shown.
And all requests in client already using only ReatTemplate

**Comment by VladimirKondr** [comment]
By wrapper i meant this 
`ResponseEntity<LogoutResponse>`
Anyway, this has been already implemented and PR was created.
So this issue can be closed.
